x-epsicube-common: &epsicube-common
  environment:
    DB_CONNECTION: pgsql
    DB_HOST: pgsql
    DB_DATABASE: ${DB_DATABASE:-epsicube}
    DB_USERNAME: ${DB_USERNAME:-postgres}
    DB_PASSWORD: ${DB_PASSWORD:-secret}
    SERVER_NAME: ${SERVER_NAME:-:80}
  volumes:
    - './:/app'
  networks:
    - epsicube

x-epsicube-build: &epsicube-build
  context: .docker/epsicube
  args:
    DOCKER_GID: '${DOCKER_GID:-999}'
    DOCKER_UID: '${DOCKER_UID:-999}'
    PHP_EXTENSIONS: '${PHP_EXTENSIONS:-bcmath curl intl mailparse mbstring opcache pcntl pdo_sqlite pdo_pgsql pgsql readline sockets xml zip}'

services:
  web:
    <<: *epsicube-common
    restart: unless-stopped
    build:
      <<: *epsicube-build
      target: web
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"

  worker:
    <<: *epsicube-common
    restart: unless-stopped
    build:
      <<: *epsicube-build
      target: worker
    init: true

  pgsql:
    build:
      context: .docker/postgres
    restart: unless-stopped
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE:-epsicube}'
      POSTGRES_USER: '${DB_USERNAME:-postgres}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'

      BACKUP_ENABLED: '${BACKUP_ENABLED:-false}'
      BACKUP_FULL_CRON: '${BACKUP_FULL_CRON:-0 3 * * 0}'
      BACKUP_DIFF_CRON: '${BACKUP_DIFF_CRON:-0 3 * * 1-6}'
      BACKUP_INCR_CRON: '${BACKUP_INCR_CRON:-0 0-2,4-23 * * *}'
      BACKUP_FULL_RETENTION: '${BACKUP_FULL_RETENTION:-52}'
      BACKUP_DIFF_RETENTION: '${BACKUP_DIFF_RETENTION:-31}'
      BACKUP_ARCHIVE_RETENTION: '${BACKUP_ARCHIVE_RETENTION:-31}'
    volumes:
      - 'pgsql:/var/lib/postgresql/data'
      - 'backups:/var/lib/pgbackrest'
    networks:
      - epsicube
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE:-epsicube}", "-U", "${DB_USERNAME:-postgres}" ]
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 2s

  # DEV
  mailpit:
    profiles: [ 'dev' ]
    restart: unless-stopped
    image: "axllent/mailpit:v1.28.2"
    ports:
      - '8025:8025'
    networks:
      - epsicube

  pgadmin:
    profiles: [ 'dev' ]
    restart: unless-stopped
    depends_on:
      pgsql:
        condition: service_healthy
    image: "dpage/pgadmin4:9"
    ports:
      - "8015:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@epsicube.dev
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - epsicube
volumes:
  pgsql:
  backups:
  pgadmin:

networks:
  epsicube:
    driver: bridge
